name: Validate PR Source

on:
  pull_request:
    branches:
      - staging
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR source branch
        run: |

          if [[ "${{ github.event.pull_request.base.ref }}" == "staging" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "❌ Solo se permiten PRs desde dev hacia staging"
            curl -s -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"state":"closed"}'
            exit 1
          fi

          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
            echo "❌ Solo se permiten PRs desde staging hacia main"
            curl -s -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"state":"closed"}'
            exit 1
          fi

          echo "✅ Validación pasada"
