name: QA Automation

on: workflow_dispatch

jobs:
  qa-automation-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install Appium
        run: |
          npm i -g appium@latest appium-uiautomator2-driver@latest appium-flutter-driver@latest

      - name: "Start Appium Server"
        run: nohup appium > appium.log 2>&1 &

      - name: Python + Robot deps
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-appiumlibrary Appium-Python-Client

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_6
          script: |
            adb install -r build/app/outputs/flutter-apk/app-debug.apk
            mkdir -p reports/android
            robot --xunit reports/android/junit.xml \
                  --output reports/android/output.xml \
                  --log reports/android/log.html \
                  --report reports/android/report.html \
                  --variablefile conf/android_staging.yaml \
                  tests

      - name: Generate JUnit Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "outputs/**/output.xml"
          check_name: "Robot JUnit Report"

      - name: Upload Robot Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-reports
          path: |
            outputs/**
            appium.log
